config/routes.rb
Rails.application.routes.draw do
  get 'subjectscore/new'

  get 'subjectscore/create'

  resources :studentsubjects
  resources :recordpayments
  resources :partials
  resources :scores
  resources :semesters
  resources :debts
  resources :groups
  resources :subjects
  resources :accounts
  resources :students
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root 'main#index'
  end

  unauthenticated :user do
    root 'main#unauthenticated'
  end

  get '/asignar' => 'students#assigment'
  post '/asignar' => 'students#assigment'
  get '/panel' => 'students#panelcontrol'
  post '/panel' => 'students#panelcontrol'

end

app/models/student.rb
class Student < ApplicationRecord
 

  belongs_to :group, optional: true
  has_many :studentsubjects
  has_many :subjects, through: :studentsubjects
  has_one :account, dependent: :delete
  has_many :debts
  belongs_to :semester, optional: true
  

  def name_lastname
    "#{name} #{lastname}"
  end

  def self.search(student)
    if student
      where('lastname LIKE ?', "%#{student}%")
    end
  end

  def self.searchgroup(group)
    @grupo = Group.where("name = ?", group)
    @grupoH = 0 
    @grupo.ids.each do |hello|
      @grupoH = hello
    end
    
    if group
      where('group_id LIKE ?', "%#{@grupoH}%")
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]


  load_and_authorize_resource 
  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:notice] = "Usuario no Autorizado"
    redirect_to root_url
  end

  def assigment
    if params[:grupo].present?
      redirect_to "/asignar?asignar=#{3}"
      puts "**************************"
      puts params
      puts "**************************"
      if params[:student].present?  
        params[:student].each do |id_student|
          estudiante = Student.find(id_student)
          puts estudiante.name
          puts "Actualizado el grupo" if estudiante.update(group_id: params[:grupo])
        end
      end

    elsif params[:materia].present?
      redirect_to "/asignar?asignar=#{1}"
      puts "**************************"
      puts params
      puts "**************************"
      if params[:student].present?  
        params[:student].each do |id_student|
          @studentsubject = Studentsubject.new
          @studentsubject.student_id = id_student
          @studentsubject.subject_id = params[:materia]
          @studentsubject.save

          #@materia = Studentsubject.where("student_id = ? AND subject_id = ?", id_student, params[:materia])
          #puts @materia.ids
          #@subjectscore = Subjectscore.new
          #@subjectscore.student_id = id_student
          #@subjectscore.subject_id = params[:materia]
          #puts @subjectscore.save
          #@subjectscore.save
        end
      end
    elsif params[:semestre].present?
      redirect_to "/asignar?asignar=#{2}"
      params[:student].each do |id_student|
        estudiante = Student.find(id_student)
        puts "Actualizado el semestre" if estudiante.update(semester_id: params[:semestre])
      end
    end

  end
  
  def panelcontrol
    if params[:student].present?
      @estudiantes = Student.search(params[:student])
    end

    if params[:grupo].present?
      redirect_to "/panel"
      puts "**************************"
      puts params
      puts "**************************"
      if params[:student].present?  
        params[:student].each do |id_student|
          estudiante = Student.find(id_student)
          puts estudiante.name
          puts "Actualizado el grupo" if estudiante.update(group_id: params[:grupo])
        end
      end

    elsif params[:materia].present?
      redirect_to "/panel"
      puts "**************************"
      puts params
      puts "**************************"
      if params[:student].present?  
        params[:student].each do |id_student|
          @studentsubject = Studentsubject.new
          @studentsubject.student_id = id_student
          @studentsubject.subject_id = params[:materia]
          @studentsubject.user_id = params[:profesor]
          @studentsubject.save
        end
      end
    elsif params[:semestre].present?
      redirect_to "/panel"
      params[:student].each do |id_student|
        estudiante = Student.find(id_student)
        puts "Actualizado el semestre" if estudiante.update(semester_id: params[:semestre])
      end
    end
    
  end
  # GET /students
  # GET /students.json
  def index
    
    if params[:student].present?
      @students = Student.search(params[:student])
    elsif params[:group].present?
      @students = Student.searchgroup(params[:group])
    else
      @students = Student.all
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params) 

    respond_to do |format|
      if @student.save
        #Start
        #When register a new student
        #Save amount of account of student
        @account = Account.new
        @totaldebts = Debt.sum(:amount)
        @account.amount = @totaldebts
        @account.student_id = @student.id
        @account.save

        #Get the id of the account and save in the student
        @student.reload
        @student.account_id = @account.id
        @student.save
        #Finish

        format.html { redirect_to @student, notice: "Student #{@student.id} was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was #{@student.id} successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:group,:semester_id,:search, :discount, :group_id, :subject_id, :name, :lastname, :tel1, :tel2, :street, :numberhome, :suburb, :registrationnumber, :banknumber, :account_id)
    end
    def account_params
      params.require(:account).permit(:amount,:student_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_asign_grupo.html.haml
%h1 Asignar grupo
=current_user.role if current_user.present?
.row
	.col-md-12
		= form_tag  do
			-#%select.js-example-basic-single{name: "state",multiple: "multiple"}
				-#%option{:value => "AL"} Alabama madre
				-#%option{:value => "WY"} Wyoming padre
			=select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
			=hidden_field_tag 'asignar', 3
			=select_tag 'grupo', options_for_select(Group.all.collect{ |u| [u.name, u.id]}),{class: "form-tag"}
			=submit_tag("Asignar")
	-#Student.all.each do |stu|
		-#.col-md-12
			=#stu.name
			Grupo >
			=s#tu.group.name


:javascript
	$( "#dropdown" ).select2({
			theme: "bootstrap"
	});
	$(document).ready(function() {
			$('.js-example-basic-single').select2();
	});

app/views/students/_asign_materia.haml
%h1 Asignar grupo
=current_user.role if current_user.present?
.row
	.col-md-12
		= form_tag  do
			-#%select.js-example-basic-single{name: "state",multiple: "multiple"}
				-#%option{:value => "AL"} Alabama madre
				-#%option{:value => "WY"} Wyoming padre
			=select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
			=hidden_field_tag 'asignar', 1
			=select_tag 'materia', options_for_select(Subject.all.collect{ |u| [u.name, u.id]}),{class: "form-tag"}
			=submit_tag("Asignar")
	-#Student.all.each do |stu|
		-#.col-md-12
			=#stu.name
			Grupo >
			=s#tu.group.name


:javascript
	$( "#dropdown" ).select2({
			theme: "bootstrap"
	});
	$(document).ready(function() {
			$('.js-example-basic-single').select2();
	});

app/views/students/_asign_semestre.haml
.row
	.col-md-12
		= form_tag  do
			=select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
			=hidden_field_tag 'asignar', 2
			=select_tag 'semestre', options_for_select(Semester.all.collect{ |u| [u.number_semester, u.id]}),{class: "form-tag"}
			=submit_tag("Asignar")



:javascript
	$( "#dropdown" ).select2({
			theme: "bootstrap"
	});
	$(document).ready(function() {
			$('.js-example-basic-single').select2();
	});

app/views/students/_form.html.haml
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      %ul
        - @student.errors.full_messages.each do |message|
          %li= message

  -#.field
    =# f.label :group_id
    =# f.text_field :group_id
  -#.field
    =# f.label :subject
    =# f.collection_select(:subjects, Subject.all, :id, :name,{})
  .row
    .col-md-4
      .field.form-group
        = f.label :name, "Nombre"
        = f.text_field :name, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :lastname, "Apellido"
        = f.text_field :lastname, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :discount, "Descuento"
        = f.number_field :discount, class: "form-control"
  .row
    .col-md-4
      .field.form-group
        = f.label :tel1, "Teléfono 1"
        = f.text_field :tel1, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :tel2, "Teléfono 2"
        = f.text_field :tel2, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :street, "Calle"
        = f.text_field :street, class: "form-control"
  .row
    .col-md-4
      .field.form-group
        = f.label :numberhome, "Numero de casa"
        = f.text_field :numberhome, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :suburb, "Colonia"
        = f.text_field :suburb, class: "form-control"
    .col-md-4
      .field.form-group
        = f.label :registrationnumber, "Matricula"
        = f.text_field :registrationnumber, class: "form-control"
  .row
    .col-md-4
      .field.form-group
        = f.label :banknumber, "Numero bancario"
        = f.text_field :banknumber, class: "form-control"
    .col-md-4
    .col-md-4
  
  .actions
    = f.submit 'Guardar', class: "btn btn-success"

app/views/students/assigment.html.haml
-@asignar = params[:asignar]
-case @asignar
  -when "1"
    = render 'asign_materia'
  -when "2"
    = render 'asign_semestre'
  -when "3"
    = render 'asign_grupo'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
.row
  .col-md-5
    %h1 Lista de estudiantes
  .col-md-2.mt-4
    =label_tag :group, "Buscar por grupo"
    =label_tag :student, "Buscar por apellido"
  .col-md-5.mt-3
    =form_tag("/students", method: "get") do
      .row
        .col-md-6
          =text_field_tag :group, params[:group], placeholder: "Grupo", class: "form-control"
        .col-md-6
          =submit_tag "Search", name: nil, class: "btn btn-info mt-2"
    =form_tag("/students", method: "get") do
      .row
        .col-md-6
          
          =text_field_tag :student, params[:student], placeholder: "Apellido(s)", class: "form-control"
        .col-md-6
          =submit_tag "Search", name: nil, class: "btn btn-info mt-2"

%table.table.table-hover
  %thead
    %tr.bg-dark.text-light
      -#%th Id
      -#%th Group
      %th{scope: "col"} Nombre
      %th{scope: "col"} Apellido
      %th{scope: "col"} Tel1
      %th{scope: "col"} Calle
      %th{scope: "col"} Numero domicilio
      %th{scope: "col"} Colonia
      %th{scope: "col"} Numero de control
      %th{scope: "col"} Numero bancario
      %th{scope: "col"} Semestre
      %th{scope: "col"} Grupo
      %th
      %th

  %tbody
    - @students.each do |student|
      %tr
        -#%td= student.id#check_box_tag "student_id", student.id , false , id: student.name
        -#%td= student.group.name if student.group.present?
        %td= student.name
        %td= student.lastname
        %td= student.tel1
        %td= student.street
        %td= student.numberhome
        %td= student.suburb
        %td= student.registrationnumber
        %td= student.banknumber
        %td= student.semester.number_semester if student.semester.present?
        %td= student.group.name
        %td= link_to 'Mostrar', student
        %td= link_to "Pagar", edit_account_path(student.account.id,student_id: student.id,ac_id: student.account.id)
        -#%td= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }

%br
-#Student.all.each_with_index do |val,index|
  =# check_box_tag @studente, val.name, false , id: index

= link_to 'Nuevo estudiante', new_student_path, class: "btn btn-warning"

app/views/students/new.html.haml
%h1 Nuevo estudiante

= render 'form'

= link_to 'Regresar', "/panel", class: "btn btn-warning"
=# link_to 'Back', students_path

app/views/students/panelcontrol.html.haml
%h3 Lista de estudiantes

.row
  .col-md-6
    %table.table.table-hover
      %thead
        %tr.bg-dark.text-light
          %th{scope: "col"} Nombre
          %th{scope: "col"} Apellido
          %th{scope: "col"} Tel1
          %th{scope: "col"}
          %th{scope: "col"} Acciones
          %th{scope: "col"}

      %tbody
        -if @estudiantes.present?
          - @estudiantes.each do |student|
            %tr
              %td= student.name
              %td= student.lastname
              %td= student.tel1
              %td= link_to 'Ver', student
              %td.text-center= link_to 'Modificar', edit_student_path(student)
              %td= link_to "Pagar", edit_account_path(student.account.id,student_id: student.id,ac_id: student.account.id)
              -#%td= link_to 'Eliminar', student, method: :delete, data: { confirm: 'Are you sure?' }
  .col-md-6
    =form_tag("/panel", method: "get") do
      =label_tag :student, "Buscar"
      =text_field_tag :student, params[:student], placeholder: "Apellido(s)", class: "form-control"
      =submit_tag "Search", name: nil, class: "btn btn-info mt-2"
-#Student.all.each_with_index do |val,index|
  =# check_box_tag @studente, val.name, false , id: index

= link_to 'Nuevo estudiante', new_student_path, class: "btn btn-warning"
%br
.row.mt-3
  .col-md-6
    %h3 Asignar materia
  .col-md-6
    %h3 Asignar grupo
.row
  .col-md-6
    = form_tag  do
      =select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
      =hidden_field_tag 'asignar', 1
      =select_tag 'materia', options_for_select(Subject.all.collect{ |u| [u.name, u.id]}),{class: "form-tag"}
      =select_tag 'profesor', options_for_select(User.where(role: "professor").collect{ |u| [u.last_name, u.id]}),{class: "form-tag"}
      =submit_tag("Asignar")

  .col-md-6
    = form_tag  do
      =select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
      =hidden_field_tag 'asignar', 3
      =select_tag 'grupo', options_for_select(Group.all.collect{ |u| [u.name, u.id]}),{class: "form-tag"}
      =submit_tag("Asignar")

.row.mt-3
  .col-md-6
    %h3 Asignar semestre
  .col-md-6
.row
  .col-md-6
    = form_tag  do
      =select_tag 'student[]', options_for_select(Student.all.collect{ |u| [u.name_lastname, u.id]}),{class: "js-example-basic-single",multiple: "multiple"}
      =hidden_field_tag 'asignar', 2
      =select_tag 'semestre', options_for_select(Semester.all.collect{ |u| [u.number_semester, u.id]}),{class: "form-tag"}
      =submit_tag("Asignar")
  .col-md-6



:javascript
  $( "#dropdown" ).select2({
    theme: "bootstrap"
  });
  $(document).ready(function() {
    $('.js-example-basic-single').select2();
  });

app/views/students/show.html.haml
%p#notice= notice
.row
  .col-md-3
    %p
      %b Group:
      = @student.group.name if @student.group.present?
  .col-md-3
    %p
      %b Name:
      = @student.name
  .col-md-3
    %p
      %b Lastname:
      = @student.lastname
.row
  .col-md-3
    %p
      %b Tel1:
      = @student.tel1
  .col-md-3
    %p
      %b Tel2:
      = @student.tel2
  .col-md-3
    %p
      %b Street:
      = @student.street
  .col-md-3
    %p
      %b Numberhome:
      = @student.numberhome
.row
  .col-md-3
    %p
      %b Suburb:
      = @student.suburb
  .col-md-3
    %p
      %b Registrationnumber:
      = @student.registrationnumber
  .col-md-3
    %p
      %b Banknumber:
      = @student.banknumber
  .col-md-3
    %p
      %b Tiene un descuento del:
      ="#{@student.discount}%"
.row
  .col-md-3
    %p
      %b Promedio:
      = @student.average
  .col-md-3
    %p
      %b Materias:
      -@student.subjects.each do |materia|
        =materia.name
-#%p
  -#%b Total a pagar:
  -# @student.studentsubjects.each do |mod|
    =#mod.firstsmodulescore


= link_to 'Modificar', edit_student_path(@student),class: "btn btn-danger"
\|
= link_to 'Regresar', students_path,class: "btn btn-warning"