config/routes.rb
Rails.application.routes.draw do
  get 'subjectscore/new'

  get 'subjectscore/create'

  resources :studentsubjects
  resources :recordpayments
  resources :partials
  resources :scores
  resources :semesters
  resources :debts
  resources :groups
  resources :subjects
  resources :accounts
  resources :students
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root 'main#index'
  end

  unauthenticated :user do
    root 'main#unauthenticated'
  end

  get '/asignar' => 'students#assigment'
  post '/asignar' => 'students#assigment'
  get '/panel' => 'students#panelcontrol'
  post '/panel' => 'students#panelcontrol'

end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource 
  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:notice] = "Usuario no Autorizado"
    redirect_to root_url
  end
  
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:total)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.haml
= form_for @score do |f|
  - if @score.errors.any?
    #error_explanation
      %h2= "#{pluralize(@score.errors.count, "error")} prohibited this score from being saved:"
      %ul
        - @score.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :total
    = f.text_field :total
  .field
    = f.label :subject_id
    = f.text_field :subject_id
  .actions
    = f.submit 'Save'

app/views/scores/edit.html.haml
%h1 Editing score

= render 'form'

= link_to 'Show', @score
\|
= link_to 'Back', scores_path

app/views/scores/index.html.haml
%h1 Listing scores

%table
  %thead
    %tr
      %th Total
      %th
      %th
      %th

  %tbody
    - @scores.each do |score|
      %tr
        %td= score.total
        %td= link_to 'Show', score
        %td= link_to 'Edit', edit_score_path(score)
        %td= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Score', new_score_path

app/views/scores/new.html.haml
%h1 New score

= render 'form'

= link_to 'Back', scores_path

app/views/scores/show.html.haml
%p#notice= notice

%p
  %b Total:
  = @score.total

= link_to 'Edit', edit_score_path(@score)
\|
= link_to 'Back', scores_path