config/routes.rb
Rails.application.routes.draw do
  get 'subjectscore/new'

  get 'subjectscore/create'

  resources :studentsubjects
  resources :recordpayments
  resources :partials
  resources :scores
  resources :semesters
  resources :debts
  resources :groups
  resources :subjects
  resources :accounts
  resources :students
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root 'main#index'
  end

  unauthenticated :user do
    root 'main#unauthenticated'
  end

  get '/asignar' => 'students#assigment'
  post '/asignar' => 'students#assigment'
  get '/panel' => 'students#panelcontrol'
  post '/panel' => 'students#panelcontrol'

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :students
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource 
  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:notice] = "Usuario no Autorizado"
    redirect_to root_url
  end
  
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Grupos

%table.table.table-hover
  %thead
    %tr.bg-dark.text-light
      %th{scope: "col"} Grupo
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= link_to 'Modificar', edit_group_path(group)
        %td= link_to 'Borrar', group, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Nuevo grupo', new_group_path, class: "btn btn"

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path