config/routes.rb
Rails.application.routes.draw do
  get 'subjectscore/new'

  get 'subjectscore/create'

  resources :studentsubjects
  resources :recordpayments
  resources :partials
  resources :scores
  resources :semesters
  resources :debts
  resources :groups
  resources :subjects
  resources :accounts
  resources :students
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root 'main#index'
  end

  unauthenticated :user do
    root 'main#unauthenticated'
  end

  get '/asignar' => 'students#assigment'
  post '/asignar' => 'students#assigment'
  get '/panel' => 'students#panelcontrol'
  post '/panel' => 'students#panelcontrol'

end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :students, through: :studentsubjects
    has_many :studentsubjects
    #has_many :students, through: :subjectscores
    has_many :subjectscores
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource 
  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:notice] = "Usuario no Autorizado"
    redirect_to root_url
  end
  
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  - if @subject.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
      %ul
        - @subject.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/subjects/edit.html.haml
%h1 Editing subject

= render 'form'

= link_to 'Show', @subject
\|
= link_to 'Back', subjects_path

app/views/subjects/index.html.haml
%h1 Materias

%table.table.table-hover
  %thead
    %tr.bg-dark.text-light
      %th{scope: "col"} Materia
      %th
      %th
      %th

  %tbody
    - @subjects.each do |subject|
      %tr
        %td= subject.name
        %td= link_to 'Modificar', edit_subject_path(subject)
        %td= link_to 'Eliminar', subject, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Nueva materia', new_subject_path, class: "btn btn-success"

app/views/subjects/new.html.haml
%h1 New subject

= render 'form'

= link_to 'Back', subjects_path

app/views/subjects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @subject.name

= link_to 'Edit', edit_subject_path(@subject)
\|
= link_to 'Back', subjects_path